# Generated by Django 3.1.7 on 2021-03-09 18:14

import app.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210308_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='setting',
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=app.helpers.RandomFileName('profiles')),
        ),
    ]
