# Generated by Django 3.1.7 on 2021-03-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_activities',
            field=models.IntegerField(blank=True, choices=[(1, 'Everyone'), (2, 'Followers'), (3, 'Only you')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_recipes',
            field=models.IntegerField(blank=True, choices=[(1, 'Everyone'), (2, 'Followers'), (3, 'Only you')], null=True),
        ),
    ]
