# Generated by Django 3.0.3 on 2020-04-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
