# Generated by Django 3.0.3 on 2020-05-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='superseded',
            field=models.BooleanField(default=False),
        ),
    ]
