# Generated by Django 3.0.3 on 2020-04-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200412_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
