# Generated by Django 3.0.3 on 2020-05-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200503_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
