# Generated by Django 3.0.3 on 2020-05-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200527_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('Vorspeise', 'Vorspeise'), ('Hauptspeise', 'Hauptspeise'), ('Suppe', 'Suppe'), ('Torte und Kuchen', 'Torte und Kuchen')], max_length=64),
        ),
    ]
