# Generated by Django 3.0.3 on 2021-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200529_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='etno',
            new_name='cuisine',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='cat_ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='parent_recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pinned',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='superseded',
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('Vorspeise', 'Vorspeise'), ('Hauptspeise', 'Hauptspeise'), ('Suppe', 'Suppe'), ('Torte und Kuchen', 'Torte und Kuchen'), ('Nachspeise', 'Nachspeise')], max_length=64),
        ),
    ]
