# Generated by Django 3.1.7 on 2021-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210308_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='guests',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.Guest'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
