# Generated by Django 3.0.3 on 2020-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200508_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
