# Generated by Django 3.1.7 on 2021-03-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210309_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='type',
        ),
        migrations.AddField(
            model_name='dish',
            name='course',
            field=models.IntegerField(blank=True, choices=[(1, 'Vorspeise'), (2, 'Hauptspeise'), (3, 'Nachspeise')], null=True),
        ),
    ]
