# Generated by Django 3.1.7 on 2021-03-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20210311_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='cuisine',
        ),
        migrations.AlterField(
            model_name='dish',
            name='course',
            field=models.IntegerField(blank=True, choices=[(1, 'First course'), (2, 'Main course'), (3, 'Dessert')], null=True),
        ),
    ]
