# Generated by Django 3.1.7 on 2021-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20210311_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cuisine',
            field=models.IntegerField(blank=True, choices=[(1, 'Austrian'), (2, 'British'), (3, 'Italian')], null=True),
        ),
    ]
