# Generated by Django 3.1.7 on 2021-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_dish_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='guests',
            field=models.ManyToManyField(blank=True, to='recipes.Guest'),
        ),
    ]
