# Generated by Django 3.1.7 on 2021-03-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20210312_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='datetime',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default='2001-01-01'),
            preserve_default=False,
        ),
    ]
