# Generated by Django 3.1.7 on 2021-03-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_historicalrecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cuisine',
            field=models.IntegerField(blank=True, choices=[(1, 'Austrian'), (2, 'British'), (3, 'Italian'), (4, 'American')], null=True),
        ),
    ]
