# Generated by Django 3.1.7 on 2021-03-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20210319_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.dish'),
        ),
    ]
