# Generated by Django 3.1.7 on 2021-03-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210321_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrecipe',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='vegan',
        ),
    ]
